task-5.1-code-update: added table component with filtering asc/desc
Admin-Portal-VDS/Admin-Portal pull request #17
Opened 2024-12-24 10:13 UTC by vanshika-dargan-18

Task Overview:

Created a Reusuable Table Component Similar to One in VBC Admin Portal. It also implements sorting in ascending or descending order. Populated with sample data as of now coming from json/tableData.json. 
<img width="1512" alt="Screenshot 2024-12-24 at 3 05 57 PM" src="https://github.com/user-attachments/assets/8e9f45e7-4e1c-4bc7-b136-576fa7d35f77" />

2024-12-24 10:55 UTC, malaypandey98 approved these changes

2024-12-24 11:17 UTC, Dys-Mn11 approved these changes

2024-12-24 11:46 UTC, pratikjoshivonage requested changes

2024-12-24 11:46 UTC, pratikjoshivonage commented on src/components/dashboard/body/AdminBody.vue
> +    return {
please simplify with spread operator
```
return {
  ...tableData,
};

```

2024-12-24 11:46 UTC, pratikjoshivonage commented on src/components/common/TableComponent.vue
> +  background-image: url('../../assets/both-arrows.svg');
please use absolute url instead of relative.

2024-12-24 11:46 UTC, pratikjoshivonage commented on src/components/common/TableComponent.vue
> +  background-image: url('../../assets/up-arrow.svg');
please use absolute url instead of relative.

2024-12-24 11:51 UTC, pratikjoshivonage requested changes

2024-12-24 11:51 UTC, pratikjoshivonage commented on src/components/common/TableComponent.vue
> +    sortedData() {
We can update the function.

    sortedData() {
      if (!this.sortKey) return this.data;
      return [...this.data].sort((a, b) => {
        const comparison = a[this.sortKey] > b[this.sortKey] ? 1 : -1;
        return this.sortOrder === 'asc' ? comparison : -comparison;
      });
    }

2024-12-26 07:03 UTC, vanshika-dargan-18 commented
@pratikjoshivonage I have addressed all issues, please check once.

2024-12-26 07:10 UTC, pratikjoshivonage commented
> @pratikjoshivonage I have addressed all issues, please check once.

Can you please check conflicts, fetch and rebase from main branch to take https://github.com/Admin-Portal-VDS/Admin-Portal/pull/19#event-15763762477 files from this commit.

2024-12-26 07:11 UTC, vanshika-dargan-18 commented
> > @pratikjoshivonage I have addressed all issues, please check once.
> 
> Can you please check conflicts, fetch and rebase from main branch to take [#19 (comment)](https://github.com/Admin-Portal-VDS/Admin-Portal/pull/19#event-15763762477) files from this commit.

Yes doing that..

2024-12-26 07:42 UTC, pratikjoshivonage approved these changes

2024-12-26 07:54 UTC, malaypandey98 approved these changes

2024-12-26 07:58 UTC, merged