Added Validation Part in loginpage and Added bg image in ForgotPassword
Admin-Portal-VDS/Admin-Portal pull request #22
Opened 2024-12-27 09:53 UTC by Shubham-rajput09

@pratikjoshivonage @malaypandey98 
cc : @vanshika-dargan-18 @Dys-Mn11 
<img width="1512" alt="Screenshot 2024-12-27 at 3 12 22 PM" src="https://github.com/user-attachments/assets/beade80c-0dc9-42bf-be3a-88051908f90b" />
<img width="1512" alt="Screenshot 2024-12-27 at 3 13 00 PM" src="https://github.com/user-attachments/assets/9ac0c4e2-ef04-484c-8043-5e0296190f0c" />

2024-12-27 15:09 UTC, pratikjoshivonage requested changes

2024-12-27 15:09 UTC, pratikjoshivonage commented on src/components/login/LoginPage.vue
> +      if (!this.username && !this.password) {
can we refactor it with one condition
```

if(!this.username || !this.password){
    return;
}
```

2024-12-27 15:09 UTC, pratikjoshivonage commented on src/components/login/LoginPage.vue
> +      // Show errors for username and password first
Maybe we can do

```
if(! isValid) {
    return;
}
```

2024-12-27 15:09 UTC, pratikjoshivonage commented on src/components/login/LoginPage.vue
> +      if (!this.username && !this.password) {
I guess this wont be needed

2024-12-30 08:04 UTC, pratikjoshivonage requested changes

2024-12-30 08:04 UTC, pratikjoshivonage commented on src/components/login/ContactUs.vue
> +              <option value="India">India</option>
<option value="India">India</option>

here option value and what to display inside option should come from array of objects and we can loop it.
Check if we can use v for like https://github.com/Admin-Portal-VDS/Admin-Portal/commit/4c882022cec98fe11aef98c2e660265c8b11f3de#diff-850bd6da8305b1dcdc873c1f252fec006d5b17456b00868a92d3a8bde3fb2cecR10 here

```

const countryDropdownOptions = [
    { value: "India", displayText: "India" },
    { value: "UK", displayText: "United Kingdom" },
];

```

2024-12-30 08:05 UTC, pratikjoshivonage commented on src/components/login/ContactUs.vue
> +              <option value="India">India</option>
same for other dropdowns like https://github.com/Admin-Portal-VDS/Admin-Portal/pull/22/files#diff-3db29592d1406a78e91361d34bbf832fbd992778b4a3df8cbbb2049958826914R49-R54

2025-01-02 08:12 UTC, pratikjoshivonage commented
A few changes
1. We should keep options as what system would understand, for eg IN should be option value and +91 should be what is displayed to user : https://www.vonage.com/contact-us/?icid=contactsales_ssologin_contactus_link
<img width="1270" alt="image" src="https://github.com/user-attachments/assets/5577da37-023e-4fcb-beb5-d24476a50d16" /> 
2. Use array of objects like below where we use dropdown. ```
const countryDropdownOptions = [
    { value: "In", displayText: "+91" },
];```

3. Apply validation on click of submit button, currently its only on blur per input field. Ideally it could be a main function that call other sub functions for validation.

4. Can you add the content that appears after successful validation and it will hide form.
<img width="1270" alt="image" src="https://github.com/user-attachments/assets/85eac885-f872-4d41-bf6c-cc000b45d26e" />

2025-01-03 08:15 UTC, pratikjoshivonage approved these changes

2025-01-03 08:22 UTC, Dys-Mn11 approved these changes

2025-01-03 08:32 UTC, merged